name: Publish package

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build, test and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-production-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-production-
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Setup Node.js with GitHub's registry
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
